#define NOB_IMPLEMENTATION
#include "nob.h"

bool build_amalgamation(const char *input_path, const char *output_path) {
    Nob_String_Builder out = {0};

    nob_sb_append_cstr(&out, "/*\n");
    nob_sb_append_cstr(&out, " * AMALGAMATED RELEASE BUILD - DO NOT EDIT THIS FILE DIRECTLY\n");
    nob_sb_append_cstr(&out, " */\n\n");

    Nob_String_Builder sfte = {0};
    if (!nob_read_entire_file(input_path, &sfte)) return false;

    Nob_String_View sfte_sv = nob_sv_from_parts(sfte.items, sfte.count);

    while (sfte_sv.count > 0) {
        Nob_String_View line = nob_sv_chop_by_delim(&sfte_sv, '\n');
        Nob_String_View trimmed = nob_sv_trim(line);

        if (nob_sv_eq(trimmed, nob_sv_from_cstr("#include \"xdg-shell.h\""))) {
            nob_sb_append_cstr(
                &out,
                "/*=== xdg-shell.h =========================================================*/\n");
            if (!nob_read_entire_file("xdg-shell.h", &out)) return false;
        } else if (nob_sv_eq(trimmed, nob_sv_from_cstr("#include \"xdg-shell.c\""))) {
            nob_sb_append_cstr(
                &out,
                "/*=== xdg-shell.c =========================================================*/\n");
            if (!nob_read_entire_file("xdg-shell.c", &out)) return false;
        } else if (nob_sv_eq(trimmed, nob_sv_from_cstr("#include \"stb_truetype.h\""))) {
            nob_sb_append_cstr(
                &out,
                "/*=== stb_truetype.h ======================================================*/\n");
            if (!nob_read_entire_file("stb_truetype.h", &out)) return false;
        } else {
            nob_sb_append_buf(&out, line.data, line.count);
            nob_sb_append_cstr(&out, "\n");
        }
    }

    nob_log(NOB_INFO, "generating amalgamation to %s", output_path);
    bool ok = nob_write_entire_file(output_path, out.items, out.count);

    nob_sb_free(out);
    nob_sb_free(sfte);

    return ok;
}

int main(int argc, char **argv) {
    NOB_GO_REBUILD_URSELF(argc, argv);

    Nob_Cmd cmd = {0};

    nob_cmd_append(&cmd, "wayland-scanner", "client-header", "xdg-shell.xml", "xdg-shell.h");
    if (!nob_cmd_run_sync(cmd)) return 1;
    cmd.count = 0;

    nob_cmd_append(&cmd, "wayland-scanner", "private-code", "xdg-shell.xml", "xdg-shell.c");
    if (!nob_cmd_run_sync(cmd)) return 1;
    cmd.count = 0;

    if (!build_amalgamation("sfte.h", "sfte_release.h")) return 1;

    nob_cmd_append(&cmd, "cc", "-Wall", "-Wextra", "-O3", "config.c", "-o", "sfte",
                   "-lwayland-client", "-lrt", "-lm", "-D_GNU_SOURCE", "-lutil", "-lxkbcommon");
    if (!nob_cmd_run_sync(cmd)) return 1;

    return 0;
}
